# Generated by Django 5.2.4 on 2025-09-06 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progresshistory',
            name='previous_image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
