# Generated by Django 5.2.4 on 2025-08-14 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('male_and_female', 'Male and Female')], max_length=20),
        ),
    ]
