# Generated by Django 5.2.4 on 2025-10-13 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suggestedworkout',
            name='gender',
        ),
        migrations.AlterField(
            model_name='suggestedworkout',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggested_workouts', to=settings.AUTH_USER_MODEL),
        ),
    ]
