# Generated by Django 5.2.4 on 2025-09-15 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_progresshistory_previous_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='video',
            field=models.FileField(max_length=255, upload_to='workout_videos/'),
        ),
    ]
