# Generated by Django 5.2.4 on 2025-09-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_progresshistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresshistory',
            name='current_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresshistory',
            name='differentiate_from_previous',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='progresshistory',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='progresshistory',
            name='tips',
            field=models.TextField(blank=True, null=True),
        ),
    ]
