# Generated by Django 5.2.4 on 2025-07-19 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestedquestion',
            old_name='name',
            new_name='question',
        ),
    ]
