# Generated by Django 5.2.4 on 2025-07-19 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0002_rename_name_suggestedquestion_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedquestion',
            name='question_de',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AddField(
            model_name='suggestedquestion',
            name='question_en',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
        migrations.AlterField(
            model_name='suggestedquestion',
            name='question',
            field=models.CharField(blank=True, max_length=1200, null=True),
        ),
    ]
