# Generated by Django 5.2.4 on 2025-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0005_resume_language_education_courseandtrainingdetail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='resumes/profile_photos/'),
        ),
    ]
