# Generated by Django 5.2.4 on 2025-07-22 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0006_resume_profile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.DateField()),
                ('job_title', models.CharField(max_length=255)),
                ('about', models.TextField()),
                ('linked_in_profile', models.URLField(blank=True, null=True)),
                ('xing_profile', models.URLField(blank=True, null=True)),
                ('applying_for', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('company_location', models.CharField(max_length=255)),
                ('hiring_manager_name', models.CharField(max_length=255)),
                ('upload_resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('why_do_you_want_this_job', models.TextField()),
                ('relevant_experience_or_skill_for_this_role', models.TextField()),
                ('specific_achievement_or_project_to_highlight', models.TextField()),
                ('keywords_or_values_to_emphasize', models.TextField()),
                ('language', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
