# Generated by Django 5.2.4 on 2025-07-22 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0007_coverletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='upload_resume',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='resume_content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
