# Generated by Django 5.2.4 on 2025-08-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_helper', '0008_remove_coverletter_upload_resume_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chathistory',
            name='answer_de',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='answer_en',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='question_de',
        ),
        migrations.RemoveField(
            model_name='chathistory',
            name='question_en',
        ),
        migrations.RemoveField(
            model_name='suggestedquestion',
            name='question_de',
        ),
        migrations.RemoveField(
            model_name='suggestedquestion',
            name='question_en',
        ),
    ]
