# Generated by Django 5.2.4 on 2025-07-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_package_name_alter_package_stripe_price_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20),
        ),
    ]
