# Generated by Django 5.2.4 on 2025-07-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_paymenthistory_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_en', models.CharField(max_length=100, null=True)),
                ('name_de', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Features',
        ),
        migrations.AlterField(
            model_name='package',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='packages', to='subscriptions.feature'),
        ),
    ]
