# Generated by Django 5.2.4 on 2025-07-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_feature_delete_features_alter_package_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='name_de',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='name_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
