# Generated by Django 5.2.4 on 2025-07-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_package_name_de_package_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='features_de',
            field=models.ManyToManyField(blank=True, null=True, related_name='packages', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='features_en',
            field=models.ManyToManyField(blank=True, null=True, related_name='packages', to='subscriptions.feature'),
        ),
        migrations.AddField(
            model_name='package',
            name='price_de',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='price_en',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='type_de',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='type_en',
            field=models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20, null=True),
        ),
    ]
