# Generated by Django 5.2.4 on 2025-07-14 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0007_package_features_de_package_features_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price_de',
        ),
        migrations.RemoveField(
            model_name='package',
            name='price_en',
        ),
    ]
