# Generated by Django 5.2.4 on 2025-07-23 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_remove_package_price_de_remove_package_price_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='pay_per_download_credits',
            field=models.IntegerField(default=0),
        ),
    ]
