# Generated by Django 5.2.4 on 2025-07-27 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_subscription_pay_per_download_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='package',
            name='type',
            field=models.CharField(choices=[('month', 'Monthly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='type_de',
            field=models.CharField(choices=[('month', 'Monthly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='type_en',
            field=models.CharField(choices=[('month', 'Monthly'), ('pay_per_download', 'Pay Per Download')], default='month', max_length=20, null=True),
        ),
    ]
