# Generated by Django 5.2.4 on 2025-07-27 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0010_incomereport_alter_package_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomereport',
            name='month',
        ),
    ]
