# Generated by Django 5.2.4 on 2025-08-06 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0012_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='package',
            name='features_de',
        ),
        migrations.RemoveField(
            model_name='package',
            name='features_en',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name_de',
        ),
        migrations.RemoveField(
            model_name='package',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='package',
            name='type_de',
        ),
        migrations.RemoveField(
            model_name='package',
            name='type_en',
        ),
    ]
