# Generated by Django 5.2.4 on 2025-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsystem',
            name='favicon',
            field=models.ImageField(blank=True, null=True, upload_to='about_system/favicon/'),
        ),
        migrations.AlterField(
            model_name='aboutsystem',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='about_system/logo/'),
        ),
        migrations.AlterField(
            model_name='socialmedia',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='about_system/social_media/'),
        ),
    ]
