# Generated by Django 5.2.4 on 2025-08-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0002_alter_aboutsystem_favicon_alter_aboutsystem_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('content', models.TextField()),
                ('type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('imprint', 'Imprint')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
