# Generated by Django 5.2.4 on 2025-09-04 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0002_openaiapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='openaiapikey',
            name='gpt_model',
            field=models.CharField(default='gpt-5-nano-2025-08-07', max_length=255),
        ),
    ]
