# Generated by Django 5.2.4 on 2025-09-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_setting', '0003_openaiapikey_gpt_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openaiapikey',
            name='gpt_model',
            field=models.CharField(default='gpt-5', max_length=255),
        ),
    ]
