# Generated by Django 5.2.4 on 2025-07-14 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='name_de',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='brand',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
