# Generated by Django 5.2.4 on 2025-07-14 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_brand_name_de_brand_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='short_description_de',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='short_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_de',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
