# Generated by Django 5.2.4 on 2025-07-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_testimonial_comment_de_testimonial_comment_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='benefit',
            name='sub_title_de',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='sub_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title_de',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='benefit',
            name='title_en',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
