# Generated by Django 5.2.4 on 2025-07-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_benefit_sub_title_de_benefit_sub_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='answer_de',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='answer_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_de',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='faq',
            name='question_en',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
