# Generated by Django 5.2.4 on 2025-07-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_faq_answer_de_faq_answer_en_faq_question_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('title_en', models.CharField(max_length=255, null=True, unique=True)),
                ('title_de', models.CharField(max_length=255, null=True, unique=True)),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_de', models.TextField(null=True)),
                ('type', models.CharField(choices=[('terms_and_conditions', 'Terms and Conditions'), ('privacy_policy', 'Privacy Policy'), ('imprint', 'Imprint')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
