# Generated by Django 5.2.4 on 2025-07-23 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowItWorkFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_de', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowItWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title_de', models.CharField(blank=True, max_length=255, null=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_de', models.TextField(null=True)),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='how_it_works/')),
                ('features', models.ManyToManyField(related_name='how_it_works', to='cms.howitworkfeature')),
            ],
        ),
    ]
