# Generated by Django 5.2.4 on 2025-07-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_howitworkfeature_howitwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='howitwork',
            name='features_de',
            field=models.ManyToManyField(null=True, related_name='how_it_works', to='cms.howitworkfeature'),
        ),
        migrations.AddField(
            model_name='howitwork',
            name='features_en',
            field=models.ManyToManyField(null=True, related_name='how_it_works', to='cms.howitworkfeature'),
        ),
    ]
