# Generated by Django 5.2.4 on 2025-07-26 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0011_howitwork_features_de_howitwork_features_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewCoachSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('short_description', models.TextField()),
                ('short_description_en', models.TextField(null=True)),
                ('short_description_de', models.TextField(null=True)),
            ],
        ),
    ]
