# Generated by Django 5.2.4 on 2025-07-26 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_interviewcoachsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_de', models.TextField(null=True)),
                ('copyright_text', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_text_en', models.CharField(blank=True, max_length=255, null=True)),
                ('copyright_text_de', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
