# Generated by Django 5.2.4 on 2025-07-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingFeatureInterestedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Upcoming Feature Interested User',
                'verbose_name_plural': 'Upcoming Feature Interested Users',
            },
        ),
    ]
