# Generated by Django 5.2.4 on 2025-07-27 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_upcomingfeatureinteresteduser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcomingfeatureinteresteduser',
            options={},
        ),
    ]
