# Generated by Django 5.2.4 on 2025-07-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_alter_upcomingfeatureinteresteduser_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_de', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_de', models.TextField(null=True)),
                ('button_text', models.CharField(max_length=255)),
                ('button_text_en', models.CharField(max_length=255, null=True)),
                ('button_text_de', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
